### ISSUE TITLE
admin not showing

### ISSUE THREAD

**Issue by petermolnar** [dshanske/bridgy-publish#1]
Hi David,

Once installed & enabled on 4.4, navigating to Bridgy Publish settings page is empty for me, no PHP errors logged. Any ideas?

**Comment by dshanske** [comment]
I will have a look.

**Comment by petermolnar** [comment]
I've figured it out; my logging had issues, the problem was the post kinds static function call, since the kinds plugin I don't have.

**Comment by dshanske** [comment]
I put a post kind call in there? Hmmm... Better fix that

**Comment by singpolyma** [comment]
Yeah, this line `kind_taxonomy::kind_defaultterms ();` makes it crash in my install also

**Comment by dshanske** [comment]
Working on Post Kinds right now for an end of year commitment. Will swing through Bridgy Publish quickly

**Comment by dshanske** [comment]
It's left over. I used the Post Kinds settings page code. I guess I left in that line. It's removed in the repo version.
