### ISSUE TITLE
No posts to Twitter if media present?

### ISSUE THREAD

**Issue by davidmead** [dshanske/bridgy-publish#12]
I've noticed when I have a photo or video embedded in the post, it doesn't show up on Twitter when posted.

I'm unsure if this is the plugin, or Brid.gy, at fault here.

I downloaded v1.1.0 but it still happens.

**Comment by dshanske** [comment]
Publish uses mf2 markup. You would have to mark up the image or video.

**Comment by davidmead** [comment]
What would I mark it up with? mf2 doesn't have a `p-media` as far as I know.

**Comment by dshanske** [comment]
u-photo for images, for example.

**Comment by davidmead** [comment]
OK. I'll try that.

**Comment by davidmead** [comment]
That worked @dshanske.

Twitter - https://twitter.com/davidmead/status/782725076747636736
Flickr - https://flic.kr/p/LSm4gR
Post  - http://djm.click/blog/b/2Nz

I did notice though, that post shows syndicating to Flickr only. Both were checked and both were posted to.

<img width="520" alt="david_john_mead" src="https://cloud.githubusercontent.com/assets/1266930/19024708/6d2a6b8c-88d7-11e6-9a6c-df30713d6f59.png">
