### ISSUE TITLE
github not in sync with WP/svn?

### ISSUE THREAD

**Issue by iamwebrocker** [dshanske/bridgy-publish#13]
hi,
just noticed this after rebasing my forked version (#5) to match the latest 1.1.1 version: the github version is still 1.1.0, so now WP reminds me of the 1.1.1 update, which I had installed previously (losing all my custom changes, of course :-)

**Comment by dshanske** [comment]
Would you be willing to try to submit any of your changes as PRs?

**Comment by iamwebrocker** [comment]
Hi David, yes, of course. Back in May I wasn't sure if I'd only be fiddling with a thing fitting my use-case only… and now I'm unsure if my may-based changes aren't too far away from what's been done towards the 1.1.1 version, so I wanted to make sure first that my code won't crash with the current version :-) If it's ok for you, I'll PR now, the code has been rebased on the current github 1.1.0 version…

**Comment by dshanske** [comment]
I'd like to continue to improve the plugin. It's limited, as the real work is done by Bridgy itself, but it can still be useful.

**Comment by iamwebrocker** [comment]
Ok, I just added the PR (#14). Sorry for the amount of commits, I had some back-and-forth while rebasing/merge some conflicts… :-)

**Comment by dshanske** [comment]
Will be incrementing the version to 1.2.0 for the next push.So resolved in that way.
