### ISSUE TITLE
Support Micropub Syndicate To Targets

### ISSUE THREAD

**Issue by dshanske** [dshanske/bridgy-publish#17]
This is a big one for me personally, as this would mean a Micropub client could tell the plugin to use Bridgy Publish to syndicate.

**Comment by miklb** [comment]
When I tested this today, I got the syndication targets to appear in Quill, (though I did have to set Twitter option to always to get it to stick), however when I chose Twitter, it didn't syndicate. Checking the post in WP admin, no option was checked.

**Comment by miklb** [comment]
Also, don't think it is related, but using latest master code, I'm seeing all 3 bridgy links on the post even though I only syndicated to Twitter. 
```
<a class="" href="https://www.brid.gy/publish/twitter"></a><a class="" href="https://www.brid.gy/publish/facebook"></a>
```

That's being appended to the note.

**Comment by dshanske** [comment]
The extra Bridgy links were fixed. As for the issue of not syndicating, I've decided to explore #18 as a better way of addressing, which means a storage rewrite again.

**Comment by miklb** [comment]
Just tested this now that I have bridgy-publish properly posting, and didn't set the option on the note to syndicate to Twitter, though I know i did check the option in Quill. Let me know how I can help debug.
