### ISSUE TITLE
Wordpress error - Warning: stripos() expects parameter 1

### ISSUE THREAD

**Issue by davidmead** [dshanske/bridgy-publish#19]
Installed the updated version. Having it default to Twitter works great. Thanks.

I have noticed this error on my pages where something has been syndicated to Twitter though

`Warning: stripos() expects parameter 1 to be string, array given in /nfs/c03/h06/mnt/56448/domains/davidjohnmead.com/html/blog/wp-includes/formatting.php on line 3774`

<img width="833" alt="david_john_mead___living_and_working_on_the_web__with_a_british_point_of_view" src="https://cloud.githubusercontent.com/assets/1266930/22175020/eeac9a2e-dfba-11e6-82b7-df6dddc1a13f.png">

Looking at that file it's to do with checking & cleaning URL's. Not sure if this to do with this plugin, *but* it only appeared after I updated.

Here's the settings for the plugin currently.

<img width="435" alt="screenshot 2017-01-21 09 22 24" src="https://cloud.githubusercontent.com/assets/1266930/22175036/465b461c-dfbb-11e6-87d0-a04e00a1fabd.png">

**Comment by dshanske** [comment]
I will try to reproduce the error on my sites. How is the update otherwise?

**Comment by davidmead** [comment]
Looks good so far @dshanske. Everything working as expected 👍

**Comment by dshanske** [comment]
I have the same error in my logs, but from November, so it must be something else. Might be a multi plugin interaction.

**Comment by miklb** [comment]
I'm seeing the error in my logs that coincide with my last published post attempting to post to bridgy, fwiw.

**Comment by dshanske** [comment]
It is hard to trace because it doesn't reference a plugin file, but I will keep trying.

**Comment by dshanske** [comment]
stripos only appears in the file in question in esc_url

**Comment by dshanske** [comment]
Which is not called by this plugin, but is called by Syndication Links, which this plugin does set display parameters for. May need a check for empty in that plugin

**Comment by davidmead** [comment]
The only other plugin that updated recently, that I have installed, is [JetPack](http://jetpack.com/). That was 4 days ago. Not sure if that would effect it.

**Comment by dshanske** [comment]
Do you have Syndication Links installed?

**Comment by miklb** [comment]
@dshanske I have syndication links installed.

**Comment by davidmead** [comment]
Yes. Version 3.0.5

**Comment by dshanske** [comment]
It is the combination of the two

**Comment by davidmead** [comment]
Just installed your update @dshanske. No error messages on my blog page now when publishing and syndicating to Twitter. The posts with the original error, still shows it.

Did notice that that when the post is published on Twitter, the syndication link is not showing.

![image](https://cloud.githubusercontent.com/assets/1266930/22217425/ffc55ec4-e170-11e6-8bb5-4441defca0be.png)

- [Blog post](http://davidjohnmead.com/blog/2017/01/23/11115/)
- [Tweet](https://twitter.com/davidmead/status/823599294892670976)

**Comment by dshanske** [comment]
Do you want it to?

**Comment by davidmead** [comment]
Yes. It used to before the update and I'd like to keep that if possible.

See [https://twitter.com/davidmead/status/822630405987823616](https://twitter.com/davidmead/status/822630405987823616) as an example.

![image](https://cloud.githubusercontent.com/assets/1266930/22249191/e97e9d02-e20f-11e6-8999-7ee0f5812ee6.png)

**Comment by dshanske** [comment]
Odd. It is showing on mine. It takes about ten seconds after the post. Uses wp-cron. I will have a look after Syndication Links is updated.

**Comment by davidmead** [comment]
On my blog, yes it shows after the cron. I'm talking about the link back to my post on Twitter.

**Comment by dshanske** [comment]
What is the omit link parameter set to by default and in the post?

**Comment by davidmead** [comment]
Omit back link is set to 'Never'

**Comment by davidmead** [comment]
Hi @dshanske. Just wondered if you had any news on this?

**Comment by dshanske** [comment]
Not yet. Looking at Syndication Links right now. Will be circling back in a few days to fix some reported bugs on my other improvements

**Comment by davidmead** [comment]
Cool. Thanks for the update :-)

**Comment by dshanske** [comment]
I made some changes. Distributing a stable release shortly. Should address.
