### ISSUE TITLE
No back link showing on Twitter

### ISSUE THREAD

**Issue by davidmead** [dshanske/bridgy-publish#25]
Updated today to Version 1.2.2 and the post from my site does get posted to Twitter, but with no backlink to the blog.

I posted [Picking music from @H_C's 'Best of 2016' lists](http://djm.click/blog/b/3bG) as the title and then content in the body. In the past this would publish to Twitter the title as the "tweet" and then the post shown underneath. In this instance it was just the title and nothing else.

![image](https://cloud.githubusercontent.com/assets/1266930/22858022/3fed051a-f080-11e6-9489-ab85b7b7c1bb.png)

 Posting it directly on Twitter, with the shortlink, gives the expected result

![image](https://cloud.githubusercontent.com/assets/1266930/22858024/6466294e-f080-11e6-88e1-94e61361e318.png)

Posting with content just in the body send that [as a tweet, but still no back link](https://twitter.com/davidmead/status/830500222417719297).

![image](https://cloud.githubusercontent.com/assets/1266930/22858033/b4e689cc-f080-11e6-823b-84b8238d8e1c.png)

Settings are:

![image](https://cloud.githubusercontent.com/assets/1266930/22858050/04ab1770-f081-11e6-8188-b9be3d0e3cd2.png)

![image](https://cloud.githubusercontent.com/assets/1266930/22858053/196754c6-f081-11e6-88da-2bce72c7b9b0.png)

**Comment by dshanske** [comment]
Can you download the fix I just pushed to the Github repo and tell me if this fixes the issue before I push a stable version?

**Comment by davidmead** [comment]
That works like a charm @dshanske :-)

![image](https://cloud.githubusercontent.com/assets/1266930/22863314/c788ca32-f10b-11e6-87d2-566e2e243360.png)

I posted tests:

- title and content

- short content, no title

- long content, no title

and all seem to post as expected. Thanks very much.
