### ISSUE TITLE
Stopped working in my install after update to 1.2.2

### ISSUE THREAD

**Issue by iamwebrocker** [dshanske/bridgy-publish#26]
after the recent update (which reversed the description(and the logic?) of the omit/show backlink per post option), now it won't publish thru bridgy, because "Bridgy Error: Couldn't find link to brid.gy/publish/twitter"
dunno if related to the above changes, but before the update it worked without adding a manual link in the post to brid.gy/publish/twitter (i thought this is what the plugin is all about - else my blog would send a webmention to brid.gy anyways if i'd add the link in the post.

**Comment by dshanske** [comment]
It didn't invert the logic, just what the UI said, due massive confusion. So show will do nothing, etc. What do your settings say?

**Comment by iamwebrocker** [comment]
it is set to "show", which also is set as default in the general plugin settings.

so, "omit -> never" is the same as "show -> always", "omit -> always" is "show -> never" and "maybe" is "maybe" ;-), ok. Just wondering if bridgy may has changed the logic, too? (not 100% sure, but I think on their site was "omit backlink", where now it says "Include link: yes no if shortened" (else I'm wondering where the "omit always/never/maybe" labeling came from ;-) )

will follow with bridgy's log, here's one of a successful test some weeks ago:

https://brid.gy/log?start_time=1481486606&key=aglzfmJyaWQtZ3lyWgsSDVB1Ymxpc2hlZFBhZ2UiM2h0dHBzOi8vd3d3LndlYnJvY2tlci5kZS8yMDE2LzEyLzExL2JyaWRneS10ZXN0LTUzLwwLEgdQdWJsaXNoGICAgICAgIAKDA

here's the log from the failed one right after the update:
https://brid.gy/log?start_time=1487004042&key=aglzfmJyaWQtZ3lyXwsSDVB1Ymxpc2hlZFBhZ2UiOGh0dHBzOi8vd3d3LndlYnJvY2tlci5kZS8yMDE3LzAyLzEzL2JyaWRneS1wdWJsaXNoLXRlc3QvDAsSB1B1Ymxpc2gYgICAgICAgAoM

**Comment by iamwebrocker** [comment]
On the other hand, even when no backlink is desired, a "webmention" link for bridgy should be inserted for it to work, so my issue cannot be related to the labeling changes… hmm.

**Comment by iamwebrocker** [comment]
I just remember, I had some issues with the recent update of the webmention plugin which were resolved by simply de- and re-activating the plugin (after a suggestion by the author) -- will try this here as well and come back.
Update: the off/on trick did not work.

**Comment by iamwebrocker** [comment]
It seems that the wp-postmeta will not be updated with the _bridgy_options:
the recent test:
![failed](https://cloud.githubusercontent.com/assets/1223080/22898676/7774ce06-f228-11e6-89da-9f3ca3660a6f.png)

an older test (I just re-checked; there's no link to brid.gy/publish/twitter/ in the post):
![worked](https://cloud.githubusercontent.com/assets/1223080/22898678/7ccd2984-f228-11e6-9db6-04093b2b2d82.png)

only  difference I see is the mf2_syndication/mf2_syndicate-to meta… there is only one "mf2_syndicate-to" meta in the database, from the latest test.

**Comment by iamwebrocker** [comment]
Just poking in the dark… in

https://github.com/dshanske/bridgy-publish/blob/master/includes/class-bridgy-postmeta.php#L206 ff

there are checks on "mf2_syndication", but in the rest of the file (fe. https://github.com/dshanske/bridgy-publish/blob/master/includes/class-bridgy-postmeta.php#L147) "mf2_syndicatate-to" is used… could this be the problem?

**Comment by dshanske** [comment]
mf2_syndication is the returned link. mf2_syndicate-to is the request to syndicate.

**Comment by dshanske** [comment]
Let me look again. It seems like I break one person's fixing the other. I am not sure why.

**Comment by iamwebrocker** [comment]
thanks!
I'm using the current 4.7.2 wordpress. the "indie web" plugins are: bridgy-publish (1.2.2), semantic linkbacks (3.3.0), syndication links (3.1.1), web actions (1.0.0dev), web mention (3.1.0), web mention form (1.0.0dev)
If you need additional info let me know.

**Comment by iamwebrocker** [comment]
looking at #25 I notice that in my general settings I neither have shortlinks or "post from excerpt" enabled. Will try this, and come back.
Update: Changing those settings didn't change the error in my install.

**Comment by iamwebrocker** [comment]
If I include an empty link to brid.gy/publish/twitter in the post it works as expected.
Just to make sure; this should not be needed, right? (asking because in #21 @snarfed mentioned a similar thing - plugin *should* add the link if neccessary) so I'm not sure if it once worked without the added link?

![manually](https://cloud.githubusercontent.com/assets/1223080/22903336/8fe35330-f238-11e6-80d6-3df514faa684.png)

**Comment by iamwebrocker** [comment]
the \_brigy\_* meta values are still not saved, it seems

![meta](https://cloud.githubusercontent.com/assets/1223080/22903490/10478b36-f239-11e6-9ada-4b64b46bf21f.png)

**Comment by iamwebrocker** [comment]
Another idea - if the meta data is now inserted via wp-footer (not in the content - see #24) - will brid.gy pick up the "publish" intend if it now may be outside of the h-entry / post wrapper?

**Comment by snarfed** [comment]
@iamwebrocker yes, the `brid.gy/publish/SILO` link can be anywhere on the page. thanks for the nudge, i've updated the docs:  https://brid.gy/about#publish-backlink

**Comment by dshanske** [comment]
The storage location was moved several revisions ago to support Micropub

**Comment by iamwebrocker** [comment]
@dshanske ok, then it seems that I haven't used the publish option since I updated to the 1.2.0 version a while ago. thanks for the info. :-)
