### ISSUE TITLE
Add Checkins

### ISSUE THREAD

**Issue by miklb** [dshanske/bridgy-publish#34]
I understand the infrastructure is in place for checkin type now, just needs to be surfaced.

Currently, the WordPress micropub plugin now supports the experimental "checkin" type coming from OwnYourSwarm, setting the `meta_key` `mf2_checkin`

OYS will add the location to the content in a `h-card` with `p-name`.

**Comment by miklb** [comment]
I should add currently post-kinds doesn't set.a kind at all, not even default to note, so the OYS PESOS breaks.

I'm more than happy to work on an interim solution while you flesh out deeper integrations with simple-location if you give me some direction on what you'd like to see.

**Comment by dshanske** [comment]
Not a Bridgy Publish problem.

**Comment by miklb** [comment]
sorry, was totally meant for post-kinds. Not sure how I got wrong repo.
