### ISSUE TITLE
Bridgy Publish not adding links to this site

### ISSUE THREAD

**Issue by dshanske** [dshanske/bridgy-publish#35]
https://doubleloop.net/2017/07/01/467/

**Comment by ngm** [comment]
@dshanske I've just updated to Wordpress 4.8 and publishing from Bridgy Publish is working again just fine.  Weird.

I was on 4.7.5 before updating.   Just for posterity's sake, this was the error I was receiving before: 

> Bridgy Error: Couldn't find link to brid.gy/publish/twitter

**Comment by dshanske** [comment]
I couldn't reproduce the issue. I have a new version of the plugin in the works that adds registration links to sign up for Bridgy. I will check the link code before the release.

**Comment by dshanske** [comment]
Since I am planning on deprecating the plugin, closing all issues.
