### ISSUE TITLE
Registering for Instragram doesn't work

### ISSUE THREAD

**Issue by svnsbck** [dshanske/bridgy-publish#37]
Hi,

It seems that registering for Instagram doesn't work. It leads to https://brid.gy/instagram/start resolving to a 405 Method Not Allowed.

Thought you might want to know.

**Comment by dshanske** [comment]
https://github.com/snarfed/bridgy/issues/752

**Comment by snarfed** [comment]
@dshanske i've fixed this on bridgy's end! one minor think you'll need to do too: add a `user_url` param to the form for instagram specifically, e.g.:

```html
<input type="hidden" name="user_url" value="https://snarfed.org/" />
```

i tried adding that to the bridgy plugin settings page instagram form manually, and it worked! it still 404ed on the last redirect back to my site, like i mentioned, but that's a separate problem.
