### ISSUE TITLE
Did not use excerpt when publishing to twitter

### ISSUE THREAD

**Issue by prtksxna** [dshanske/bridgy-publish#39]
### Versions
* PHP 5.4.45
* Wordpress 4.8
* Bridgy Publish 1.2.2

### Settings:
* Set Twitter from Post Excerpt is **checked**

### What happened?
In recently published a blog post — http://prtksxna.com/2017/07/18/1389/ — which I syndicated to Twitter using this plugin — https://twitter.com/prtksxna/status/887347617646202881. While I had set the post excerpt to…

> …leading her daughter to describe the work as painting… https://www.theguardian.com/us-news/2017/jul/15/maryam-mirzakhani-mathematician-dies-40

…and __Link Back to Post__ as __Maybe__, it used the post body to create the tweet.

### What should've happened?
It should have used the excerpt instead, as I had marked in the settings.

**Comment by miklb** [comment]
I think the issue might be a missing `class` https://github.com/dshanske/bridgy-publish/blob/master/includes/class-bridgy-postmeta.php#L296
