### ISSUE TITLE
Link Back to Post: Hide doesn't work

### ISSUE THREAD

**Issue by snarfed** [dshanske/bridgy-publish#41]
hey david! i tried the bridgy publish plugin with twitter just now, and it worked great...except it ignored my choice of _Hide_ in the _Link Back to Post_ drop-down. looks like it didn't include the `bridgy_omit_link=true` param in the webmention. here's the bridgy log:

```
Params: [('source', u'https://snarfed.org/2017-10-15_25692'), ('target', u'https://www.brid.gy/publish/twitter')]
requests.head https://snarfed.org/2017-10-15_25692 {'headers': {'User-Agent': '...'}}
Source: https://www.brid.gy/twitter/schnarfed , features [u'publish', u'listen'], status enabled, poll status ok
Publish entity: 'aglz...'
requests.get https://snarfed.org/2017-10-15_25692 {'headers': {'User-Agent': '...'}}
Converted to ActivityStreams object: ...
urlopen POST https://api.twitter.com/1.1/statuses/update.json?status=That+feeling+when+you+Google+something+obscure+and+only+find+your+own+old%2C+unhelpful+stuff.+%F0%9F%91%8E+%28https%3A%2F%2Fsnarfed.org%2F2017-10-15_25692%29 {}
```

**Comment by dshanske** [comment]
I'll see what broke. I know I tested that feature when I deployed it.

**Comment by dshanske** [comment]
Unit tests, huh?

**Comment by snarfed** [comment]
very low priority. i vote for semantic linkbacks facepile fixes over this! :P

**Comment by dshanske** [comment]
I think @pfefferle is working on caching avatars right now for that plugin.

**Comment by snarfed** [comment]
great! plenty of other facepiles issues to work on too. :P https://github.com/pfefferle/wordpress-semantic-linkbacks/issues/

**Comment by jackysee** [comment]
I've looked into it. 
The `<data class="p-bridgy-omit-link" value="true"></data>` has to be in content.

**Comment by jackysee** [comment]
created a pull request for this.
