### ISSUE TITLE
Twitter threaded replies via WP comments and syndication

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/bridgy-publish#43]
Just an idea for a rainy day:
It would be interesting to allow threaded Twitter conversations using comment webmentions and bridgy publish in combination with https://github.com/pfefferle/wordpress-webmention-for-comments.

This already works for micro.blog with webmentions directly, but could also be adapted to Twitter. 
See also conversation here: https://chat.indieweb.org/2017-11-01#t1509552057518000

**Comment by dshanske** [comment]
Since I am planning on deprecating the plugin, marking these inactive.
