### ISSUE TITLE
bridgy signup callback breaks if wordpress installed at different URL path

### ISSUE THREAD

**Issue by snarfed** [dshanske/bridgy-publish#46]
hi! looks like the buttons that send people to bridgy to sign up hard code the wordpress admin URL path as `/wp-admin/...`:

https://github.com/dshanske/bridgy-publish/blob/master/includes/class-bridgy-config.php#L322

...but many wordpress sites have it at a different path. eg. mine is at `/w/wp-admin/...` this makes the bridgy signup flow 404 when it gets redirected back to the wordpress site. (originally mentioned back in https://github.com/dshanske/bridgy-publish/issues/37#issuecomment-315799817.)

i think you can fix it by using [`admin_url()`](https://codex.wordpress.org/Function_Reference/admin_url) instead of hard-coding `/wp-admin/`.

**Comment by asuh** [comment]
Funny you mention this, I found this bug last night and [submitted a pull request](https://github.com/dshanske/bridgy-publish/pull/45) :smile:
