### ISSUE TITLE
Timing issues with triggering webmention to bridgy

### ISSUE THREAD

**Issue by Ruxton** [dshanske/bridgy-publish#50]
Bridgy sends are happening so fast that they seem to be occuring before my image is in place.

This is my process:

1. post to instagram
2. ownyourgram sees that and posts via micropub with syndications
3. save_post fires off in bridgy_publish (at this point attachments are saved)
4. publish_post fires off in bridgy_publish (at this point, webmentions are sent to bridgy)
5. Bridgy doesn't see the image and therefore doesn't upload it to FB or Twitter
6. If i return to bridgy and preview the original URL, it shows the image

If I remove step 4, wait a second after step 3 and manually send the webmention to Bridgy, it all comes out as I'd expect.

I've tried triggering step 4 (bridgy's publish_post) from WordPresses publish_post action. I've also tried adjusting wordpress-micropub to create the post as draft, add the attachments and then publish it.  Both of those running together and still have the same issue.

**Comment by dshanske** [comment]
Since I am planning on deprecating the plugin, marking these closed.
