### ISSUE TITLE
tell users that bridgy can't publish private posts

### ISSUE THREAD

**Issue by snarfed** [dshanske/bridgy-publish#53]
right now the plugin evidently doesn't pay attention to post status, so it lets you POSSE a private post, and then silently fails since bridgy can't see it. [reported in IRC today](https://chat.indieweb.org/wordpress/2018-01-09#t1515469770677600):

> I think my bug was because I was testing out whether a private post could still be syndicated to Facebook and when I went to publish, nothing happened. I checked to make sure the setting was enabled in the Dashboard, I also verified that I connected to Facebook via Brid.gy.

**Comment by dshanske** [comment]
According to the code, it doesn't fire on a private post, so I trigger a custom error.
