### ISSUE TITLE
Missing newline in Bridgy Registration area

### ISSUE THREAD

**Issue by jernst** [dshanske/bridgy-publish#54]
![screen shot 2018-01-20 at 16 26 09](https://user-images.githubusercontent.com/874785/35189416-eb9a7b54-fdfe-11e7-9817-61b9a33badb7.png)

The two separate messages/links should be on separate lines, or at least seperated by a white space. This is 1.3.3.

**Comment by miklb** [comment]
Looks like there is a PR for that https://github.com/dshanske/bridgy-publish/pull/51
