### ISSUE TITLE
Terminology: "maybe"

### ISSUE THREAD

**Issue by jernst** [dshanske/bridgy-publish#55]
One of the options for "Link back to post" is "maybe". It's unclear what that means. Is there a better label that could be used?

**Comment by miklb** [comment]
`maybe` directly relates to the terminology [bridgy uses for linking back](https://brid.gy/about#omit-link)

**Comment by jernst** [comment]
What about using, to quote right from that same page, "if shortened" instead of "maybe"? That is something that would give me the right hint what might be happening when.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/bridgy-publish/issues/55" class="u-in-reply-to"></a>@jernst Thanks for your nudges and suggestions for improving the UI in the indieweb suite of plugins!

**Comment by dshanske** [comment]
Seems like I changed this
