### ISSUE TITLE
Support GitHub

### ISSUE THREAD

**Issue by miklb** [dshanske/bridgy-publish#56]
Bridgy now supports stars (likes), replies and new issues in early beta. I believe the Issue kind is coming to post-kinds.

Forgive me if this is already being worked on.

**Comment by dshanske** [comment]
Do I Support Github now?

(Originally published at: https://github.com/dshanske)

**Comment by chrisaldrich** [comment]
[Support GitHub · Issue #56 · dshanske/bridgy-publish](https://github.com/dshanske/bridgy-publish/issues/56) _( GitHub)_

> Bridgy now supports stars (likes), replies and new issues in early beta. I believe the Issue kind is coming to post-kinds. Forgive me if this is already being worked on.

@snarfed and @dshanske  are brilliant!

With any luck, this will be my first POSSE reply to Github via my WordPress site using [Bridgy Publish](https://brid.gy/about#github-issue-comment).

(Originally published at: http://boffosocko.com/2018/02/28/first-reply-to-github-with-bridgy-publish/)

**Comment by chrisaldrich** [comment]
[Support GitHub · Issue #56 · dshanske/bridgy-publish](https://github.com/dshanske/bridgy-publish/issues/56#issuecomment-368283029) by David Shanske _( GitHub)_

> Do I Support Github now?

🎉

![](http://1.gravatar.com/avatar/d5fb4e498fe609cc29b04e5b7ad688c4?s=42&d=mm&r=pg)

## Author: Chris Aldrich

I'm a biomedical and electrical engineer with interests in information theory, complexity, evolution, genetics, signal processing, theoretical mathematics, and big history. I'm also a talent manager-producer-publisher in the entertainment industry with expertise in representation, distribution, finance, production, content delivery, and new media. [ View all posts by Chris Aldrich ](http://www.boffosocko.com)

**Comment by miklb** [comment]
Am I missing something? I don't see an option for GitHub in bridgy publish

**Comment by miklb** [comment]
Sorry, somehow didn't get a clean pull from master.
