### ISSUE TITLE
"Bridgy Publish Requires the WordPress Webmention Plugin"

### ISSUE THREAD

**Issue by iamwebrocker** [dshanske/bridgy-publish#6]
this appears in the WP-admin /dashboard after the recent update to Webmention v.2.6.0 a few hours ago.
It appears that the check for the class "WebMentionPlugin" fails, since now the class is named "[Webmention_Plugin](https://github.com/pfefferle/wordpress-webmention/blob/master/webmention.php#L24)" in the webmention plugin code.
As a [hot fix](https://github.com/iamwebrocker/bridgy-publish/commit/5cc9f2b37dfc818b4d155aff2e5514bd6a64aa2a) I changed line [23f](https://github.com/dshanske/bridgy-publish/blob/master/bridgy-publish.php#L23) to 

```
if (!class_exists("WebMentionPlugin") && !class_exists("Webmention_Plugin"))
        { ... 
```

but I'm sure there is a better way :-)

**Comment by dshanske** [comment]
I will deploy an update that checks for the new class.
