### ISSUE TITLE
Bridgy Twitter Callback  - 406 Not Acceptable

### ISSUE THREAD

**Issue by mediaformat** [dshanske/bridgy-publish#66]
Trying to Register for twitter
> https://myurl.tld/wp-admin/admin.php?page=bridgy_options&service=twitter&result=success&key=xxx&user=https%3A%2F%2Fbrid.gy%2Ftwitter%2Fuser_slug
Not Acceptable!
An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.

I also tried going directly to brid.gy, seeing I was logged into twitter, I tried adding the website from the edit-sites page.

Any suggestions?

**Comment by dshanske** [comment]
Well, the plugin is not currently maintained, as the functionality is being merged elsewhere. But you can register directly with bridgy on the site. But this plugin technically doesn't need to get any data back from bridgy during registration. It just uses the return to hide the registration option, so you should be fine.

**Comment by dshanske** [comment]
Still want to help  Does posting work?

**Comment by mediaformat** [comment]
Hmmm, I switched themes from Independent Publisher to SemPress and now it seems to work!

But its good to know its no longer supported.
