### ISSUE TITLE
Sending wrong part of post as Twitter reply

### ISSUE THREAD

**Issue by davidmead** [dshanske/bridgy-publish#8]
Hi @dshanske.

I'm having an issue when using this to reply to tweets.

If I write my reply in WP, check the Bridgy Publish for Twitter, then paste the URL I'm replying to in Post Properties, and hit publish I get this in Twitter...

<img width="656" alt="david_mead_on_twitter___well_done__sodevious__next_up__pokemon_go__ __https___t_co_0qty4w4gb6__" src="https://cloud.githubusercontent.com/assets/1266930/16935040/cf8bdc50-4d29-11e6-8c51-14af70a7be2d.png">

It posts, but not as a reply.

If I do the same thing, **but** mark is a reply in Post Kinds I get this on my blog...

<img width="693" alt="david_john_mead___living_and_working_on_the_web__with_a_british_point_of_view" src="https://cloud.githubusercontent.com/assets/1266930/16935062/0705aabc-4d2a-11e6-9750-c4aae5ef41ef.png">

which displays this on Twitter...

<img width="649" alt="blog-reply_tweet_format_wrong" src="https://cloud.githubusercontent.com/assets/1266930/16935068/14d4b1ba-4d2a-11e6-8a1a-12a1341263da.png">

Any ideas? Is there a specific order I should be doing, or is this just a bug?

**Comment by dshanske** [comment]
Bridgy Publish parses your site to generate the tweet. So it partially depends on how it is marked up. But @snarfed has added ways to override that and be more specific. I may add support for them to the plugin.

**Comment by davidmead** [comment]
That'd be great @dshanske. Also, what is the Instagram checkbox for? I didn't think they allowed posting anything apart through the web/app.

**Comment by dshanske** [comment]
I'm working on this at the moment, and will try to add additional functionality for it in the next version.

**Comment by dshanske** [comment]
Last version supported using the Excerpt for the Twitter output.
